# Numpy

In [26]:
import numpy as np

my_list = [3,2,5,7,11,4]

# Kreirana nova lista Numpy iz obicne
my_np_array = np.array(my_list)

# Unosenje novog clana ako ne postoji, odnosno update ako postoji
new_list = np.insert(my_np_array, 6, 555)

# Append
new_list = np.append(new_list,2)
new_list = np.append(new_list,[1,1,2])
new_list = np.delete(new_list, [0,2])

# Vectors

my_npa_1 = np.array([2,3,3])
my_npa_2 = np.array([1,1])
my_npa_3 = np.array([1,1,2])

    # Sabiranje vektora
print(my_npa_1 + my_npa_3)
    
    # Mnozenje skalarnih vektora
print(my_npa_1 * 2)

    # Dot product
A=np.array([2,3])
B=np.array([1,2])

print(A.dot(B))
print(np.sum(A*B))
print(new_list)

[3 4 5]
[4 6 6]
8
8
[  2   7  11   4 555   2   1   1   2]
